
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Video Latar & Musik</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body, html {
      height: 100%;
      font-family: monospace;
      color: white;
    }

    .video-bg {
      position: fixed;
      top: 0; left: 0;
      width: 100%;
      height: 100%;
      object-fit: cover;
      z-index: -1;
    }

    .overlay {
      position: relative;
      z-index: 1;
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.4);
      text-align: center;
      padding: 20px;
    }

    button {
      margin-top: 20px;
      padding: 10px 20px;
      font-size: 18px;
      background-color: #ff69b4;
      border: none;
      color: white;
      border-radius: 5px;
      cursor: pointer;
    }
  </style>
</head>
<body>

  <!-- Video sebagai background -->
  <video autoplay muted loop id="bg-video" class="video-bg">
    <source src="background.mp4" type="video/mp4" />
    Browser kamu tidak mendukung video.
  </video>

  <!-- Overlay konten -->
  <div class="overlay">
    <h1>hai nabila sayang</h1>
    <p>klik tombol di bawah untuk dengarkan musiknya ya</p>
    <button onclick="putarMusik()">putar musik</button>
  </div>

  <!-- Audio -->
  <audio id="musik" src="musik.mp3"></audio>

  <script>
    function putarMusik() {
      const musik = document.getElementById("musik");
      musik.play();
    }
  </script>
</body>
</html>
